---
- name: include ufw role
  include_role:
    name: ufw

- name: enable ufw for powerdns_exporter
  ufw:
    comment: 'Prometheus powerdns_exporter'
    rule: allow
    src: '{{ item }}'
    proto: tcp
    port: '{{ prometheus_pdns_exporter_listen_port }}'
    direction: in
  loop: '{{ prometheus_pdns_exporter_src_access }}'
